/* A Leading retail company wants to better understand its customers' shopping behavior 
in order to improve sales, customer satisfaction, and long-term loyalty. 
The management team has noticed changes in purchasing patterns across 
demographics, product categories, and sales channels (online vs. offline). 
They are particularly interested in uncovering which factors, such as discounts, 
reviews, seasons, or payment preferences, drive consumer decisions and repeat purchases.
You are tasked with analyzing the company's consumer behavior dataset to answer the 
following overarching business question:

"How can the company leverage consumer shopping data to identify trends, improve 
customer engagement, and optimize marketing and product strategies?" */

USE customer_shopping_behaviour;  

select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    Customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
	customer_id, 
    purchase_amount
    from customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
Select 
	item_purchased,
	ROUND(avg(review_rating),2) as avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
limit 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
	shipping_type,
    ROUND(avg(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select 
	item_purchased,
	SUM(CASE When discount_applied = 'Yes' Then 1 ELSE 0 END) AS discounted_purchases,
	ROUND(SUM(CASE When discount_applied = 'Yes' Then 1 ELSE 0 END) * 100.0 / count(*), 2) AS discount_rate
FROM customer
Group by item_purchased
order by discount_rate desc
limit 5; 

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;





-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

-- Q11. Total Revenue with discount applied according to customer segment (loyal, returning and new)
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    SUM(purchase_amount) AS total_revenue_with_discount
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY customer_segment;